#Set the verbose!
/control/verbose 0
/tracking/verbose 0
/run/verbose 0



/MRPC/det/Gapsize 30 30 2.5 mm
/MRPC/det/Glasssize 30 30 0.7 mm
/MRPC/det/Honeysize 30 30 6 mm
/MRPC/det/PCBsize 30 30 0.7 mm
/MRPC/det/Mylarsize 30 30 0.18 mm
/MRPC/det/NumberOfGap 1
/MRPC/det/StepMax 0.05 mm
/MRPC/det/PitchWidth 20 mm
/run/initialize
/MRPC/det/update

/MRPC/Rec/doWrite 1






#Set the view frame
/vis/open OGL 600x600-0+0
/vis/drawVolume
/vis/viewer/flush


#Set the view parameters!
/vis/viewer/zoom 1
/vis/viewer/set/viewpointThetaPhi 45 45 deg

#Add the trajectories and hits!
/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate

/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event



#Set the colors of particles!
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/set 1 red
#/vis/modeling/trajectories/drawByCharge-0/set -1 yellow
#/vis/modeling/trajectories/drawByCharge-0/set 0 green

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set mu- green
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
/vis/modeling/trajectories/drawByParticleID-0/set gamma blue
/vis/modeling/trajectories/drawByParticleID-0/set proton orange 

#Run particles!
#/gun/particle mu-
#/gun/energy 5 MeV
/run/beamOn 300
